module.exports = {
    'birth_date must be yyyy-mm-dd format': '"birth_date must be yyyy-mm-dd format',
    'profile has been successfully updated': 'Поздравляем, профиль успешно обновлён!',
    'sharing': 'Рассказать о вебсайте',
    'something wrong': 'Что-то пошло не так',
    'fill profile': 'Заполнить профиль',
    'login to account': 'Вход в личный кабинет',
    'history of accounting':'История транзакций',
    'phone is already in use':'Введённый Вами телефон уже используется, пожалуйста, укажите другой',
    'user already has phone':'Введённый Вами телефон уже используется, пожалуйста, укажите другой',
    'email is already in use':'Введённый Вами email уже используется, пожалуйста, укажите другой',
    'email is not valid':'Проверьте правильность указания email',
    'points_will_be':'Баллы будут зачислены',
    'order_detail': 'Детали заказа ',
    'phone or email or origin_user_id': 'Укажите телефонный номер или email ',

    'purchase': 'Заказ',
    'gift_purchase': 'Подарок',
    'badge': 'Бейджик',
    'registration': 'Регистрация',
    'referral': 'Регистрация друга',
    'referred': 'Регистрация по приглашению',
    'referred_purchase': 'Покупка приглашенного пользователя',
    'promocode': 'За ввод промокода',
    'enter_group': 'Вступление в группу ',
    'share_purchase': 'Рассказ о покупке в ',
    'social_share': 'Рассказ в ',
    'share_badge': 'Рассказ о бейджике в ',
    'earn_badge': 'Получен бейджик ',
    'edit_profile_complete': 'Поздравляем! Вы успешно выполнили задание, Вам начислено 20 баллов',
    'custom_action': 'Начислены баллы',
    'custom_action_negative': 'Списаны баллы'
};